### ISSUE TITLE
Feature Request: Add a dispatch effect

### ISSUE THREAD

**Issue by chmac** [tomekkleszcz/redux-saga-promise-actions#1]
Firstly, thanks for this package, it looks awesome, and especially that its in TypeScript.

At first I found the [package from Adobe](https://github.com/adobe/redux-saga-promise) which is very similar, but written in JavaScript. :-( It has 1 feature which I don't see in your package, and which I guess is simple to add. It exposes a [new effect called `dispatch`](https://github.com/adobe/redux-saga-promise#dispatching-a-promise-action-in-a-saga). This effect returns the `put` or `putResolve` effect based on whether the dispatched action is a promise action or not. It's a nice wrapper that makes it easier to always use `dispatch` and know that promise actions will be awaited automatically.

The code for the effect is quite simple, here's a direct link:

https://github.com/adobe/redux-saga-promise/blob/fd5c964e295ebc12cb1d342037f0a87490217700/src/index.js#L78-L94

**Comment by tomekkleszcz** [comment]
@chmac Thank you for the kind words. I've implemented the `dispatch` helper as you wish. It is available to use in the `1.1.1` version.

**Comment by chmac** [comment]
@tomekkleszcz That's EPIC, thanks a lot for the super fast response. I was holding off deploying this package wondering how to solve this in the meantime, but you deployed this so fast I'll start using it tomorrow!
