### ISSUE TITLE
Error running build

### ISSUE THREAD

**Issue by tifsolu** [tomekkleszcz/redux-saga-promise-actions#19]
Love this project, anyone running into this typescript issues when building.

Failed to compile.

MenuSafetyLLCVer1/node_modules/redux-saga-promise-actions/dist/index.d.ts(27,126):        
'>' expected.  TS1005

    25 |  * @param {Z} Z Failure action payload
    26 |  */
  > 27 | export declare function createPromiseAction<Type extends TypeConstant, X, Y, Z>(type: Type): <X, Y, Z>() => PromiseActionSet<`${Type}_REQUEST`, `${Type}_SUCCESS`, `${Type}_FAILURE`, X, Y, Z>;
       |                                                                                                                              ^
    28 | /**
    29 |  * Create an object containing three action-creators.
    30 |  * @param {string} requestType Request action type

error Command failed with exit code

**Comment by tomekkleszcz** [comment]
Hi,

What TypeScript version do you use in your project? Please check if upgrading to 4.1.3 version will fix the issue.

**Comment by tifsolu** [comment]
Thank you, I’ll give that a try. Don Sent from Mail for Windows 10 From: Tomek KleszczSent: Thursday, January 14, 2021 1:26 AMTo: tomekkleszcz/redux-saga-promise-actionsCc: tifsolu; AuthorSubject: Re: [tomekkleszcz/redux-saga-promise-actions] Error running build (#19) Hi,What TypeScript version do you use in your project? Please check if upgrading to 4.1.3 version will fix the issue.—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by tomekkleszcz** [comment]
@tifsolu Please open a new issue if you will encounter the issue again. Side note: I use the library in a number of projects (both React and React Native) without hassle.

**Comment by tifsolu** [comment]
> 
> 
> @tifsolu Please open a new issue if you will encounter the issue again. Side note: I use the library in a number of projects (both React and React Native) without hassle.

Yeah let you know what I found, my project is using react-app-rewired.
