### ISSUE TITLE
Typescript as a devDependency?

### ISSUE THREAD

**Issue by chmac** [tomekkleszcz/redux-saga-promise-actions#5]
Tried to install this from git, but I was missing the `dist/` folder. Then I cloned, ran `yarn`, and got a "tsc not found" error. What about adding a specific TypeScript version as a devDependency?

Also, what about adding a lockfile? Maybe you're using npm? I usually pick my package manager based on the lockfile, or default to yarn if there isn't one. :-)

**Comment by tomekkleszcz** [comment]
@chmac If you could create a pull request and add typescript as a devDependency it would be much appreciated. :) I use 4.1.2 version on my local machine.

I use yarn as a package manager. I will add lockfile after I finish my work.

**Comment by tomekkleszcz** [comment]
I've added typescript as a dev dependency and yarn.lock file to the repository.

**Comment by chmac** [comment]
@tomekkleszcz Missed the comment about sending a PR, would have done that earlier today, apologies.

Pulled the latest and it's working great here, builds no issues.
