### ISSUE TITLE
Interop with typed-redux-saga?

### ISSUE THREAD

**Issue by chmac** [tomekkleszcz/redux-saga-promise-actions#6]
Firstly, you've already answered a TON of my questions and added AWESOME new features, so feel free to silently ignore or close this topic if you've reached your limit!

I'm trying to get `putResolve()` from [typed-redux-saga](https://github.com/agiledigital/typed-redux-saga) to play nicely with this package. The typted-redux-saga package introduces some extra types so that I can do:

```typescript
import {putResolve} from 'typed-redux-saga'

const actionCreators = createPromiseAction(
  "foo/request",
  "foo/success",
  "foo/failure"
)<undefined, { token: "string" }, { error: Error }>();

function* saga() {
  const val = yield* putResolve(actionCreators.request());
}
```

In the scenario above, TypeScript can figure out the type of `val`. However, when I try it with a PromiseAction, the resulting type of `val` is `PromiseAction<string, PayloadType, ResolveType>`.

I can't figure out how to tell TypeScript that the result is the `ResolveType`. My TypeScript fu is way over stretched here. The generics and so on are just not something I know well enough.

I'm wondering if I can request that the typed-redux-saga package adds support for PromiseActions so that the types it ships understand how a PromiseAction is treated. I was trying to figure out how to do that to submit a PR or open a discussion there, but thus far I'm lost. If you have any pointers that would push me in the right direction, I'll be most grateful. 👍 

EDIT: VSCode shows the following type for val:

```typescript
const val: PromiseAction<"foo/request", undefined, {
    token: "string";
}>
```

So `val.meta.promiseAction` is of type `boolean`.

**Comment by tomekkleszcz** [comment]
@chmac Can you also attach a block of code where you define `actionCreator`?

**Comment by chmac** [comment]
@tomekkleszcz Yep, sorry, original example wasn't clear at all, I updated it. The `actionCreator` as it was is a PromiseAction.request. I've added that to make it clearer.

**Comment by tomekkleszcz** [comment]
@chmac I don't use `redux-typed-saga` in my projects. I've checked out this is a declaration for `putResolve` function:
```export function putResolve<A extends Action>(
  action: A,
): SagaGenerator<A, PutEffect<A>>;```

As you can see the return value typed as the action which is provided as the argument of the `putResolve` function which in your case totally incorrect - you provide `actionCreators.request()` and you would expect the return value to be `{token: 'string'}`, but it is the type of the action you provide instead.

There are three solutions to this problem:
1. Use `putResolve` from `redux-saga`
2. Update `dispatch` helper in my library to type the return type correctly
3. Create a PR to `typed-redux-saga` and fix the problem

I advise you to use the first solution for now. As soon as I close other feature requests I think I may start to work on updating `dispatch` helper.

**Comment by chmac** [comment]
@tomekkleszcz Thanks for taking the time to look at this for me, I appreciate it.

I started out using `putResolve()` from redux-saga, but in that case I get the type of `val` as `unknown`. The trick `typed-redux-saga` uses is to use `yield*` instead of `yield` and then a babel macro to transform the whole thing at runtime. As I understand it, the issue is that TypeScript has no way of knowing what that the Redux Saga middleware will resolve into the `yield` call.

I also tried the `dispatch` helper from your package, again I get `type unknown` for `val`.

Do you have an example of how I could use `putResolve` from `redux-saga`, or preferably, your `dispatch` function and have TypeScript know what the type of `val` will be? That would be the best case, I could drop the `typed-redux-saga` package altogether.

**Comment by tomekkleszcz** [comment]
I think in your case the following solution would work:
```
import {putResolve} from 'redux-saga'

const actionCreators = createPromiseAction(
  "foo/request",
  "foo/success",
  "foo/failure"
)<undefined, { token: "string" }, { error: Error }>();

function* saga() {
  const val: { token: "string" } = yield putResolve(actionCreators.request());
}
```

**Comment by chmac** [comment]
@tomekkleszcz Yeah, I can typecast the return value. But if I get the type wrong, there's no checking. That's the aim of the `typed-redux-saga` package, to avoid that potential mistake.

OK, thanks a lot for all the input. I'll try digging further into the `putResolve` types from `redux-typed-saga`, it's definitely not an issue in your package. I actually get the correct type, just that the `putResolve()` type definition in `typed-redux-saga` doesn't understand that it should take the `ResolveType` and not the whole thing.

Thanks again for the help on this. 👍 👍 👍

**Comment by chmac** [comment]
@tomekkleszcz Looking at this fresh today, I realise that I think the typing in the typed-redux-saga (and not the redux-typed-saga) package is wrong for `putResolve()`. I opened [an issue](https://github.com/agiledigital/typed-redux-saga/issues/351). Thanks again for the help, closing this as it's not an issue in this package I realise.
